#############################################################################
# Makefile for building: katalog
# Generated by qmake (2.01a) (Qt 4.5.0) on: Sun Sep 27 14:54:13 2009
# Project:  katalog.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile katalog.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Iinclude -Iui/src -Iui/include
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtNetwork -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = lib/

####### Files

SOURCES       = src/CFilm.cxx \
		src/CMainWindow.cxx \
		src/main.cxx \
		src/CThread.cxx \
		src/util.cxx \
		src/CKatalog.cxx \
		src/CSettingWindow.cxx ui/src/moc_CMainWindow.cpp \
		ui/src/moc_CThread.cpp \
		ui/src/moc_CKatalog.cpp \
		ui/src/moc_CSettingWindow.cpp \
		ui/src/qrc_ressource.cpp
OBJECTS       = lib/CFilm.o \
		lib/CMainWindow.o \
		lib/main.o \
		lib/CThread.o \
		lib/util.o \
		lib/CKatalog.o \
		lib/CSettingWindow.o \
		lib/moc_CMainWindow.o \
		lib/moc_CThread.o \
		lib/moc_CKatalog.o \
		lib/moc_CSettingWindow.o \
		lib/qrc_ressource.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		katalog.pro
QMAKE_TARGET  = katalog
DESTDIR       = 
TARGET        = katalog

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui/include/ui_main.h ui/include/ui_settings.h ui/include/ui_add.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: katalog.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile katalog.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile katalog.pro

dist: 
	@$(CHK_DIR_EXISTS) lib/katalog1.0.0 || $(MKDIR) lib/katalog1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) lib/katalog1.0.0/ && $(COPY_FILE) --parents include/CFilm.h include/CFilm.hxx include/CMainWindow.h include/CMainWindow.hxx include/CThread.h include/CThread.hxx include/util.h include/CException.h include/CException.hxx include/CKatalog.h include/CKatalog.hxx include/CSettingWindow.h lib/katalog1.0.0/ && $(COPY_FILE) --parents ui/ressource.qrc lib/katalog1.0.0/ && $(COPY_FILE) --parents src/CFilm.cxx src/CMainWindow.cxx src/main.cxx src/CThread.cxx src/util.cxx src/CKatalog.cxx src/CSettingWindow.cxx lib/katalog1.0.0/ && $(COPY_FILE) --parents ui/main.ui ui/settings.ui ui/add.ui lib/katalog1.0.0/ && $(COPY_FILE) --parents lang/en_EN.ts lib/katalog1.0.0/ && (cd `dirname lib/katalog1.0.0` && $(TAR) katalog1.0.0.tar katalog1.0.0 && $(COMPRESS) katalog1.0.0.tar) && $(MOVE) `dirname lib/katalog1.0.0`/katalog1.0.0.tar.gz . && $(DEL_FILE) -r lib/katalog1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: ui/src/moc_CMainWindow.cpp ui/src/moc_CThread.cpp ui/src/moc_CKatalog.cpp ui/src/moc_CSettingWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) ui/src/moc_CMainWindow.cpp ui/src/moc_CThread.cpp ui/src/moc_CKatalog.cpp ui/src/moc_CSettingWindow.cpp
ui/src/moc_CMainWindow.cpp: ui/include/ui_main.h \
		include/CThread.h \
		include/CThread.hxx \
		include/CMainWindow.hxx \
		include/CMainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/CMainWindow.h -o ui/src/moc_CMainWindow.cpp

ui/src/moc_CThread.cpp: include/CThread.hxx \
		include/CThread.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/CThread.h -o ui/src/moc_CThread.cpp

ui/src/moc_CKatalog.cpp: include/CKatalog.hxx \
		include/CKatalog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/CKatalog.h -o ui/src/moc_CKatalog.cpp

ui/src/moc_CSettingWindow.cpp: ui/include/ui_settings.h \
		include/CSettingWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/CSettingWindow.h -o ui/src/moc_CSettingWindow.cpp

compiler_rcc_make_all: ui/src/qrc_ressource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) ui/src/qrc_ressource.cpp
ui/src/qrc_ressource.cpp: ui/ressource.qrc \
		ui/icon_film.png \
		ui/icon_connexion.png \
		ui/icon_stop.png
	/usr/bin/rcc -name ressource ui/ressource.qrc -o ui/src/qrc_ressource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui/include/ui_main.h ui/include/ui_settings.h ui/include/ui_add.h
compiler_uic_clean:
	-$(DEL_FILE) ui/include/ui_main.h ui/include/ui_settings.h ui/include/ui_add.h
ui/include/ui_main.h: ui/main.ui
	/usr/bin/uic-qt4 ui/main.ui -o ui/include/ui_main.h

ui/include/ui_settings.h: ui/settings.ui
	/usr/bin/uic-qt4 ui/settings.ui -o ui/include/ui_settings.h

ui/include/ui_add.h: ui/add.ui
	/usr/bin/uic-qt4 ui/add.ui -o ui/include/ui_add.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

lib/CFilm.o: src/CFilm.cxx 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lib/CFilm.o src/CFilm.cxx

lib/CMainWindow.o: src/CMainWindow.cxx 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lib/CMainWindow.o src/CMainWindow.cxx

lib/main.o: src/main.cxx 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lib/main.o src/main.cxx

lib/CThread.o: src/CThread.cxx 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lib/CThread.o src/CThread.cxx

lib/util.o: src/util.cxx 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lib/util.o src/util.cxx

lib/CKatalog.o: src/CKatalog.cxx 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lib/CKatalog.o src/CKatalog.cxx

lib/CSettingWindow.o: src/CSettingWindow.cxx 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lib/CSettingWindow.o src/CSettingWindow.cxx

lib/moc_CMainWindow.o: ui/src/moc_CMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lib/moc_CMainWindow.o ui/src/moc_CMainWindow.cpp

lib/moc_CThread.o: ui/src/moc_CThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lib/moc_CThread.o ui/src/moc_CThread.cpp

lib/moc_CKatalog.o: ui/src/moc_CKatalog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lib/moc_CKatalog.o ui/src/moc_CKatalog.cpp

lib/moc_CSettingWindow.o: ui/src/moc_CSettingWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lib/moc_CSettingWindow.o ui/src/moc_CSettingWindow.cpp

lib/qrc_ressource.o: ui/src/qrc_ressource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lib/qrc_ressource.o ui/src/qrc_ressource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

